import { Alignments } from "../enums/alignment";
import { ArmorClassArmor } from "./armor-class-armor";
import { MonsterAction } from "./monster-action";
import { MonsterProficiency } from "./monster-proficiency";
import { MonsterSpecialAbility } from "./monster-special-ability";
import { Reference } from "../info/reference";
import { Senses } from "./senses";
import { Sizes } from "../enums/sizes";
import { Speed } from "./speed";
import { ArmorConditionSpell } from "./armor-class-condition";
import { ArmorClassSimple } from "./armor-class-simple";
import { ArmorClassSpell } from "./armor-class-spell";

export class Monster {
    index = '';
    name = '';
    url = '';
    desc: string[] = [];
    charisma = 0;
    constitution = 0;
    dexterity = 0;
    intelligence = 0;
    strength = 0;
    wisdom = 0;
    image = '';
    size = Sizes.Medium;
    type = '';
    subtype = '';
    alignments = Alignments.neutral;
    armor_class: (ArmorClassArmor | ArmorConditionSpell | ArmorClassSimple | ArmorClassSpell)[] = [];
    hit_points = 0;
    hit_dice = '';
    hit_points_roll = '';
    actions: MonsterAction[] = [];
    legendary_actions: MonsterAction[] = [];
    challenge_rating = 0;
    condition_immunities: Reference[] = [];
    damage_immunities: string[] = [];
    damage_resistances: string[] = [];
    damage_vulnerabilities: string[] = [];
    forms: Reference[] = [];
    languages = '';
    proficiency = new MonsterProficiency();
    reactions: MonsterAction[] = [];
    senses = new Senses();
    special_abilities: MonsterSpecialAbility[] = [];
    speed = new Speed();
    xp = 0;
}